### ISSUE TITLE
Add current value method to indicators

### ISSUE THREAD

**Issue by semtexzv** [greyblake/ta-rs#1]
It would be very nice to have a method that would evaluate an indicator, and return it's current value. Current interface, that returns value only when new item is added is extremely clunky.

**Comment by greyblake** [comment]
Hey! Thanks for creating an issue.
I thought that this may be needed (sometimes I found myself in the situation, when it could be useful).

Probably I'll add a new method:
```rust
fn last(&self) -> Self::Output;
```
What do you think?

**Comment by greyblake** [comment]
@semtexzv What do you think about the suggestion?

It looks like it must return `Option<Output>`, `None` is possible if `indicator.last()` is called, before any of input values were provided to an indicator.

**Comment by greyblake** [comment]
Looks like the discussion is not alive, so I am closing the issue.
