### ISSUE TITLE
Addition of volume based Indicators

### ISSUE THREAD

**Issue by shreyasdeotare** [greyblake/ta-rs#10]
As volume is the only other variable with price, addition of volume based indicators would be a good feature.
Can we add Money flow Indicator to start with?

**Comment by shreyasdeotare** [comment]
/// Money Flow Index (MFI).
///
/// The MFI is an volume and price based oscillator which gives moneyflow over n periods.
/// MFI is used to measure buying and selling pressure.
/// MFI is also known as volume-weighted RSI.
///
/// # Formula
///
/// Typical Price(TP) = (High + Low + Close)/3
/// Raw Money Flow(RMF) = Typical Price x Volume
/// RMF is positive when currnt TP is greater that previous period TP and
/// negative when current TP is less than preivous TP
/// Positive money flow (PMF)- calculated by adding the money flow of all the days RMF is positive
/// Negative money flow (PMF)- calculated by adding the money flow of all the days RMF is negative
/// Money Flow Index(MFI) = 100 * (PMF / (PMF + NMF) )
///
/// Where:
///
/// _tp_ - typical price
/// _rmf_ - raw MF
/// _pmf_ - positive MF
/// _nmf_ - negative MF
/// _mfr_ - MF ratio
///
/// # Parameters
///
/// * _n__ - number of periods, integer greater than 0
///
/// # Example
///
///```
/// use ta::indicators::MoneyFlowIndex;
/// use ta::Next;
///
/// let mut mfi  = MoneyflowIndex::new(3).unwrap();
///
/// let mfi_1 = mfi.next(100.0, 98.0, 99.0, 10101010)
///                     // high, low , close,volume
///
/// # Links
/// ![Moeny Flow Index, Wikipedia](https://en.wikipedia.org/wiki/Money_flow_index)
/// ![Money Flow Index, stockcharts] (https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:money_flow_index_mfi)

**Comment by greyblake** [comment]
Hey, thanks for the proposal!
Do you mean [MoneyFlowIndex](https://en.wikipedia.org/wiki/Money_flow_index)?
Looks interesting. 
If you'd like to implement it I am 100% OK :)

**Comment by shreyasdeotare** [comment]
@greyblake Yes same MoneyFlowIndex
