### ISSUE TITLE
DataItemIncomplete when trying to unwrap DataItem build

### ISSUE THREAD

**Issue by OfekShochat** [greyblake/ta-rs#48]
I tried to make a DataItem vector from a Candle vector. but when I do this:
```
DataItem::builder()
          .high(i.high.to_f64().unwrap())
          .low(i.low.to_f64().unwrap())
          .close(i.close.to_f64().unwrap())
          .volume(i.volume.to_f64().unwrap())
          .build().unwrap()
```
(`i` is a Candle in a for loop) it throws a DataItemIncomplete error.

**Comment by OfekShochat** [comment]
wasnt included in the documentation but there's also an open field?

**Comment by greyblake** [comment]
Yes, I guess you can see it from the examples: https://docs.rs/ta/0.5.0/ta/struct.DataItem.html
