### ISSUE TITLE
wonder how to handle big number, like for cryptocurrency

### ISSUE THREAD

**Issue by davidxiaowws** [greyblake/ta-rs#54]
need to use https://github.com/paupino/rust-decimal ( etc) or no?

Thanks

**Comment by greyblake** [comment]
It depends on how precise it needs to be. If it's not too crazy crypto with 100 leading zeros, you can simply cast your decimal into f64 and feed it into indicators. Technical indicators are not ledgers, you do not need to super-duper precise like in banking.
